# Generated by Django 3.1.5 on 2021-03-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        ("users", "0002_remove_cbluser_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="cbluser",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="department.department",
            ),
            preserve_default=False,
        )
    ]
