# Generated by Django 3.1.5 on 2021-04-08 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_remove_visit_blocked_students'),
        ('users', '0006_auto_20210328_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='', verbose_name='reason for remove a student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='blocked_students')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visit.visit', verbose_name='Visit')),
            ],
        ),
    ]
