# Generated by Django 3.1.5 on 2021-03-01 09:50

from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Question Title"),
                ),
            ],
            options={"verbose_name_plural": "questiones"},
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=10, verbose_name="question type"),
                ),
            ],
            options={"verbose_name_plural": "question types"},
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.IntegerField(
                        choices=[(1, "Before Visit"), (2, "After Visit")],
                        verbose_name="Report Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Is Portion active"
                    ),
                ),
                (
                    "is_for_staff",
                    models.BooleanField(default=False, verbose_name="Is for staff"),
                ),
                (
                    "to_beactive_in",
                    models.DateField(
                        blank=True,
                        default=report.models.Report.tommorrow,
                        verbose_name="The activate date",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        to="report.Question", verbose_name="Report Questions"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="report.questiontype",
                verbose_name="question type",
            ),
        ),
        migrations.CreateModel(
            name="Needle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Activated"),
                ),
                (
                    "init_value",
                    models.CharField(
                        max_length=250, verbose_name="Proposed Value for Question Type"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="report.question",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={"verbose_name_plural": "needles"},
        ),
        migrations.CreateModel(
            name="ComplexReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is report Active"),
                ),
                (
                    "is_for_staff",
                    models.BooleanField(default=False, verbose_name="Is for staff"),
                ),
                (
                    "after_report",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "title": "2"},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="after",
                        to="report.report",
                        verbose_name="The Questions after visit",
                    ),
                ),
                (
                    "before_report",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True, "title": "1"},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="before",
                        to="report.report",
                        verbose_name="The Questions before visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="answer")),
                (
                    "file_to",
                    models.FileField(
                        blank=True,
                        upload_to="storage/answers/",
                        verbose_name="Uploaded File",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="report.question",
                        verbose_name="Question",
                    ),
                ),
            ],
        ),
    ]
