# Generated by Django 3.1.5 on 2021-03-01 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import visit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("report", "0001_initial"),
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0001_initial"),
        ("meeting", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitSites",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("location", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Starts in"
                    ),
                ),
                (
                    "to",
                    models.DateField(
                        default=visit.models.Visit.week_after, verbose_name="Ends in"
                    ),
                ),
                ("objectives", models.TextField()),
                (
                    "code",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=8, unique=True
                    ),
                ),
                (
                    "main_img",
                    models.ImageField(
                        blank=True,
                        upload_to="storage/visits/",
                        verbose_name="Main image",
                    ),
                ),
                (
                    "img_one",
                    models.ImageField(
                        blank=True,
                        upload_to="storage/visits/",
                        verbose_name="Other image",
                    ),
                ),
                (
                    "img_two",
                    models.ImageField(
                        blank=True,
                        upload_to="storage/visits/",
                        verbose_name="Other image",
                    ),
                ),
                (
                    "complex_report",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="report.complexreport",
                        verbose_name="visit report",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="department.department",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="equipment.equipment",
                        verbose_name="equipments",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        limit_choices_to={
                            "is_staff": True,
                            "is_super_admin": False,
                            "is_superuser": False,
                        },
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="leader",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Leader",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="meeting.meeting",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.visitsites",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        limit_choices_to={
                            "is_staff": False,
                            "is_super_admin": False,
                            "is_superuser": False,
                        },
                        related_name="visit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="course.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Benefician",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        help_text="select a gender",
                        max_length=6,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="visit.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("date", models.DateField(verbose_name="Due to")),
                ("desc", models.TextField(verbose_name="Activities were in the visit")),
                (
                    "leader",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Leader",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="visit.visit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.CharField(max_length=250, verbose_name="Achievement Desc"),
                ),
                ("date", models.DateTimeField(auto_now=True, verbose_name="Done at")),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="visit.visit"
                    ),
                ),
            ],
        ),
    ]
