# Generated by Django 3.1.5 on 2021-03-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("report", "0001_initial"), ("visit", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="complex_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="report.complexreport",
                verbose_name="visit report",
            ),
        )
    ]
