# Generated by Django 3.1.5 on 2021-04-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_auto_20210406_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='blocked_students',
        ),
    ]
