# Generated by Django 3.1.5 on 2021-03-01 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("visit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="students",
            field=models.ManyToManyField(
                limit_choices_to={
                    "is_staff": False,
                    "is_super_admin": False,
                    "is_superuser": False,
                },
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="visit.visit"
            ),
        ),
        migrations.AddField(
            model_name="approveduservisit",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={
                    "is_staff": False,
                    "is_super_admin": False,
                    "is_superuser": False,
                },
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="The Attendant",
            ),
        ),
        migrations.AddField(
            model_name="approveduservisit",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="visit.visit",
                verbose_name="The requested Visit",
            ),
        ),
    ]
