# Generated by Django 3.1.5 on 2021-03-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("attendance", "0002_auto_20210301_1150")]

    operations = [
        migrations.AlterField(
            model_name="approveduservisit",
            name="parent_signture",
            field=models.ImageField(
                blank=True, default="", upload_to="storage/signtures/"
            ),
        )
    ]
